# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba8ec2fe70770b20bfe4e4f5044dda838d9edb4a91d2977c20ca1ebcdbc6bd99d1752d71ca20b5de4e84f5d7bc8790f86699f71513c9b7f5031ba35199ab182

test:
  secret_key_base: 9110f3dfb2056d04c435143b229340a441c2d6f22e823058df03b86234e55000dcf4cc98c6af2fa4fe1f2941e8d1dd7bb8e7ffee4556840ea629f89b7837dfad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
